### PR TITLE
Fix Wifi connection issues - public networks and password handling

### LINKED ISSUE #58: Unable to connect to public wifi from sleexxx settings
Able to login to wifi networks that require a password, but public wifi hotspots won't activate without expanding and entering a password

There is no password on the public wifi, so you can't expand, and you can't connect..

### PR DESCRIPTION
**Pull request by Chirag8405**
# Fix WiFi Connection Issues - Public Networks & Password Handling

##  Fixes Issues
- Closes #58  - Unable to connect to public wifi from sleex settings

### Core Fixes
- **Public WiFi Support**: Enable connection to open networks without password prompts
- **Incorrect Password Detection**: Implement specific error messages for authentication failures  
- **WiFi Toggle Fix**: Restore proper WiFi enable/disable functionality
- **Enhanced Error Handling**: Fast authentication failure detection (1s vs 3s+ previously)

### Technical Implementation
- **NetworkManager Integration**: Enhanced device state monitoring with specific error reasons
- **Dynamic Security Detection**: Proper handling of networks changing security settings
- **UI/UX Improvements**: Clean error message positioning without layout conflicts
- **ScriptModel Compliance**: Fix invalidate() errors with proper refresh triggers

### Files Modified
- `src/share/sleex/plugins/src/Sleex/services/network.cpp` - Core NetworkManager logic
- `src/share/sleex/modules/settings/Wifi.qml` - UI enhancements and error handling

##  Testing Done
- [x] Public hotspot connection (no password required)
- [x] Secured network connection (WPA2/WPA3 with password)
- [x] Incorrect password detection and user feedback
- [x] Network security change detection (open ↔ protected)
- [x] WiFi toggle enable/disable functionality  
- [x] Error message display and UI stability

##  Backward Compatibility
- ✅ No breaking changes to existing API
- ✅ All existing WiFi functionality preserved
- ✅ Enhanced error handling is additive only

##  Additional Notes
This PR resolves the core WiFi connectivity issues that prevented users from connecting to public networks while maintaining all existing functionality for secured networks.

### CODE REVIEW

File: src/share/sleex/plugins/src/Sleex/services/network.cpp [hunk 1]
```diff
@@ -256,21 +308,65 @@ void Network::rescanWifi() {
...
             onConnectionActivated,
-            this
+            callbackData
         );
-    } else {
+    } else if (connection && !password.isEmpty()) {
+        // Network security changed from open to protected - recreate connection
+        
+        GError *deleteError = nullptr;
+        gboolean deleteResult = nm_remote_connection_delete(connection, nullptr, &deleteError);
```
Comment (LeVraiArdox) [inline src/share/sleex/plugins/src/Sleex/services/network.cpp]: `nm_remote_connection_delete` is deprecated. Can you use something else such as `nm_remote_connection_delete_async` ?

File: src/share/sleex/modules/settings/Wifi.qml [hunk 2]
```diff
@@ -71,39 +139,135 @@ ContentPage {
...
-            font.pixelSize: 30
+        ColumnLayout {
             Layout.alignment: Qt.AlignHCenter | Qt.AlignVCenter
-            visible: !Network.wifiEnabled
+            visible: !(Network.wifiEnabled || false)
+            spacing: 10
+
+            MaterialSymbol {
+                Layout.alignment: Qt.AlignHCenter
+                text: "wifi_off"
```
Comment (LeVraiArdox) [inline src/share/sleex/modules/settings/Wifi.qml]: use the "signal_wifi_off" icon, it looks better.

File: src/share/sleex/modules/settings/Wifi.qml [hunk 3]
```diff
@@ -71,39 +139,135 @@ ContentPage {
...
+                Layout.alignment: Qt.AlignHCenter
+                text: "Turn on WiFi to see available networks"
+                color: Appearance.colors.colOnLayer1
+                font.pixelSize: Appearance.font.pixelSize.large
+                horizontalAlignment: Text.AlignHCenter
+            }
+        }
+
+        // Connection error display
+        Rectangle {
```
Comment (LeVraiArdox) [inline src/share/sleex/modules/settings/Wifi.qml]: It would be better to put that as a red text under the current entry.

File: src/share/sleex/modules/settings/Wifi.qml [hunk 4]
```diff
@@ -190,38 +362,93 @@ ContentPage {
...
-                                onClicked: {
-                                    if (!checked) {
-                                        Network.disconnectFromNetwork();
-                                    } else {
-                                        root.connectingToSsid = networkItem.modelData.ssid;
-                                        Network.connectToNetwork(networkItem.modelData.ssid, "");
-                                        networkItem.expanded = false
-                                    }
+                            // Forget network button for known networks
+                            RippleButton {
```
Comment (LeVraiArdox) [inline src/share/sleex/modules/settings/Wifi.qml]: Here, do not put this button here.

File: src/share/sleex/modules/settings/Wifi.qml
Comment (LeVraiArdox) [inline src/share/sleex/modules/settings/Wifi.qml:1]: I don't really like the design of this. The forget button is right next to two other important buttons, that's an UX inconsistency. Also, the wifi input is now visible even when the network is known. And What you can do is keep the previous layout but use RippleButtonWithIcon for the forget button. As a bonus, do the same for the expand.

**Review by LeVraiArdox — CHANGES_REQUESTED** [review]
Told you everything is needed. It's almost all visual stuff. The backend works fine. Good job!

**Comment by Chirag8405** [comment]
@LeVraiArdox  I have made the necessary changes as adviced by you.

File: src/share/sleex/modules/settings/Wifi.qml [hunk 5]
```diff
@@ -173,55 +320,111 @@ ContentPage {
...
-                            StyledSwitch {
-                                id: toggleSwitch
-                                scale: 0.80
-                                Layout.fillWidth: false
-                                checked: networkItem.modelData.active
-                                enabled: networkItem.modelData.isKnown
+                            RippleButtonWithIcon {
+                                visible: networkItem.modelData?.isSecure || false
+                                materialIcon: networkItem.expanded ? "keyboard_arrow_up" : "keyboard_arrow_down"
+                                mainText: ""
```
Comment (LeVraiArdox) [inline src/share/sleex/modules/settings/Wifi.qml]: Maybe "expand" instead of blank ?

File: src/share/sleex/modules/settings/Wifi.qml [hunk 6]
```diff
@@ -388,6 +555,21 @@ ContentPage {
...
                                         }
 
+
+
+                                    }
+                                }
+
+                                // Forget button for known networks, separated at bottom
+                                RippleButtonWithIcon {
+                                    Layout.fillWidth: true
```
Comment (LeVraiArdox) [inline src/share/sleex/modules/settings/Wifi.qml]: Here. Remove this one, it looks ugly when fillwidthed (that's not a word but you get it)

**Review by LeVraiArdox — CHANGES_REQUESTED** [review]
Minor changes are demanded. But it's clearly better than the previous time!

Also, look at this

image

When we enter incorrect password, it says incorrect password for a second, but then it show this. Possibly the next message. Can you fix that ? If not, it's okay, we can keep it like that.

File: src/share/sleex/modules/settings/Wifi.qml (hunk 5 above)
Comment (Chirag8405) [reply src/share/sleex/modules/settings/Wifi.qml]: I kept it blank as it displays that text beside that icon.

Comment (LeVraiArdox) [reply src/share/sleex/modules/settings/Wifi.qml]: Yeah, I think it looks better with the text

Comment (Chirag8405) [reply src/share/sleex/modules/settings/Wifi.qml]: Ok will add that, but I was thinking to add text to be revealed when hovered over the arrow

Comment (Chirag8405) [reply src/share/sleex/modules/settings/Wifi.qml]: image

image

The second image is of hover to reveal.

Comment (LeVraiArdox) [reply src/share/sleex/modules/settings/Wifi.qml]: On the second image, you can see there is a weird right padding on the button. In that case, the normal Ripple Button is better

Comment (Chirag8405) [reply src/share/sleex/modules/settings/Wifi.qml]: image

Used normal Ripple Button. If this works, then i can push the final commit. I have solved the configuring connection issue and removed the fill width as you have suggested.

Comment (LeVraiArdox) [reply src/share/sleex/modules/settings/Wifi.qml]: Good

**Review by LeVraiArdox — APPROVED** [review]
LGTM

Bonus if you want, the wifi icon seems to be marked as no signal when you are not connected to them. I can do it myself, but if you want to do it I can let you do it. 

Else, we can merge, it's all good.

**Comment by Chirag8405** [comment]
I have added the wifi signal icons according to their strengths. Also previously the expanded menu had security which always showed up as undefined, so fixed that too.

**Comment by LeVraiArdox** [comment]
Thank you for your contribution, it's really helpful!
